trigger:
 - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build_stage
    jobs:
      - job: jobA
        pool:
          vmImage: ubuntu-latest
        steps:
         - task: Maven@1
           inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: false
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            sonarQubeRunAnalysis: false


  - stage: test_stage
    dependsOn: build_stage
    condition: succeeded()
    jobs:
      - job: jobA
        steps:
          -  script: echo "test"
  - stage: deploy
    dependsOn: build_stage
    jobs:
      -  job: 
         steps:
            - task: PublishBuildArtifacts@1
              inputs:
                PathtoPublish: '$(Build.ArtifactStagingDirectory)'
                ArtifactName: 'drop'
                publishLocation: 'Container'

