trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  PersonalAccessToken: $(PersonalAccessToken)  # Ensure this is defined securely in your pipeline

steps:
  - script: |
      echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\"" > settings.xml
      echo "          xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"" >> settings.xml
      echo "          xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0" >> settings.xml
      echo "                              https://maven.apache.org/xsd/settings-1.0.0.xsd\">" >> settings.xml
      echo "  <servers>" >> settings.xml
      echo "    <server>" >> settings.xml
      echo "      <id>purushothamareddyazure</id>" >> settings.xml
      echo "      <username>purushothamareddyazure</username>" >> settings.xml
      echo "      <password>$(PersonalAccessToken)</password>" >> settings.xml  # Replace with your PAT
      echo "    </server>" >> settings.xml
      echo "  </servers>" >> settings.xml
      echo "</settings>" >> settings.xml
    displayName: 'Generate settings.xml'

  # Use this settings.xml for Maven builds
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      options: '--settings settings.xml -X'  # Enable debug output
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
    displayName: 'Run Maven Build with Custom settings.xml'

  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'deploy'
      options: '--settings settings.xml'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
    displayName: 'Run Maven Build with Custom settings.xml'
