trigger:
 - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build_stage
    jobs:
      - job: jobA
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: echo "mvn clean package"

  - stage: test_stage
    jobs:
      - job: jobA
        steps:
          -  script: echo "test"
  - stage: 
    jobs:
      -  job: 
         steps:
           -  script: echo "deploy"
